from repositories.database.soil_humidity import SoilHumidityTable
from repositories.database.battery_state import BatteryStateTable
from repositories.database.watering_schedule import WateringSchedule